### ISSUE TITLE
fails to build with clang 17.0.6 in Termux

### ISSUE THREAD

**Issue by StevanWhite** [igraph/python-igraph#758]
**Describe the bug**
In Android app Termux:
    `pip install igraph`
fails to build -- evidently a disagreement about proper programming

/data/data/com.termux/files/usr/tmp/pip-install-vlfgqpr2/igraph_381da76a988b414e9aa9f74e48f265cd/vendor/source/igraph/src/io/graphml.c:1613:39: error: incompatible function pointer types passing 'void (*)(void *, xmlErrorPtr)' (aka 'void (*)(void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       1613 |     xmlSetStructuredErrorFunc(&state, &igraph_i_libxml_structured_error_handler);
            |  

**To reproduce**
Steps or minimal example code to reproduce the problem.

This is Termux on Android 12.
the compiler is `clang 17.0.6`
I had previously installed a lot of development libraries using 'pkg',
and run 
`apt-get upgrade`
`pip list --outdated`
to make sure everything is up to date.

**Version information**
Which version of igraph are you using and where did you obtain it?

`igraph 0.11.3`
got via
`pip install igraph`

**Comment by szhorvat** [comment]
This is already fixed in C/igraph, and will be fixed in Python as well as soon as a release based on igraph 0.10.9 or 0.10.10 is issued.

**Comment by ntamas** [comment]
`python-igraph` 0.11.4 is being built in CI right now and will be published in a few hours, so you can just upgrade to 0.11.4 and it should be okay.

**Comment by StevanWhite** [comment]
I tried
`export IGRAPH_CMAKE_EXTRA_ARGS="-DIGRAPH_WARNINGS_AS_ERRORS=OFF"`
No apparent effect.

Did 
`pip install -U igraph`
see
`igraph-0.11.4.tar.gz`

It installed properly.

THANKS!
